// Code generated by entc, DO NOT EDIT.

package volume

const (
	// Label holds the string label denoting the volume type in the database.
	Label = "volume"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldVolumeType holds the string denoting the volumetype field in the database.
	FieldVolumeType = "volume_type"

	// EdgeDrugs holds the string denoting the drugs edge name in mutations.
	EdgeDrugs = "drugs"

	// Table holds the table name of the volume in the database.
	Table = "volumes"
	// DrugsTable is the table the holds the drugs relation/edge.
	DrugsTable = "drugs"
	// DrugsInverseTable is the table name for the Drug entity.
	// It exists in this package in order to avoid circular dependency with the "drug" package.
	DrugsInverseTable = "drugs"
	// DrugsColumn is the table column denoting the drugs relation/edge.
	DrugsColumn = "volume_id"
)

// Columns holds all SQL columns for volume fields.
var Columns = []string{
	FieldID,
	FieldVolumeType,
}

var (
	// VolumeTypeValidator is a validator for the "VolumeType" field. It is called by the builders before save.
	VolumeTypeValidator func(string) error
)
