// Code generated by entc, DO NOT EDIT.

package form

const (
	// Label holds the string label denoting the form type in the database.
	Label = "form"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFormType holds the string denoting the formtype field in the database.
	FieldFormType = "form_type"

	// EdgeDrugs holds the string denoting the drugs edge name in mutations.
	EdgeDrugs = "drugs"

	// Table holds the table name of the form in the database.
	Table = "forms"
	// DrugsTable is the table the holds the drugs relation/edge.
	DrugsTable = "drugs"
	// DrugsInverseTable is the table name for the Drug entity.
	// It exists in this package in order to avoid circular dependency with the "drug" package.
	DrugsInverseTable = "drugs"
	// DrugsColumn is the table column denoting the drugs relation/edge.
	DrugsColumn = "form_id"
)

// Columns holds all SQL columns for form fields.
var Columns = []string{
	FieldID,
	FieldFormType,
}

var (
	// FormTypeValidator is a validator for the "FormType" field. It is called by the builders before save.
	FormTypeValidator func(string) error
)
