// Code generated by entc, DO NOT EDIT.

package form

import (
	"github.com/Piichet-3-/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// FormType applies equality check predicate on the "FormType" field. It's identical to FormTypeEQ.
func FormType(v string) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFormType), v))
	})
}

// FormTypeEQ applies the EQ predicate on the "FormType" field.
func FormTypeEQ(v string) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFormType), v))
	})
}

// FormTypeNEQ applies the NEQ predicate on the "FormType" field.
func FormTypeNEQ(v string) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldFormType), v))
	})
}

// FormTypeIn applies the In predicate on the "FormType" field.
func FormTypeIn(vs ...string) predicate.Form {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Form(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldFormType), v...))
	})
}

// FormTypeNotIn applies the NotIn predicate on the "FormType" field.
func FormTypeNotIn(vs ...string) predicate.Form {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Form(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldFormType), v...))
	})
}

// FormTypeGT applies the GT predicate on the "FormType" field.
func FormTypeGT(v string) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldFormType), v))
	})
}

// FormTypeGTE applies the GTE predicate on the "FormType" field.
func FormTypeGTE(v string) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldFormType), v))
	})
}

// FormTypeLT applies the LT predicate on the "FormType" field.
func FormTypeLT(v string) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldFormType), v))
	})
}

// FormTypeLTE applies the LTE predicate on the "FormType" field.
func FormTypeLTE(v string) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldFormType), v))
	})
}

// FormTypeContains applies the Contains predicate on the "FormType" field.
func FormTypeContains(v string) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldFormType), v))
	})
}

// FormTypeHasPrefix applies the HasPrefix predicate on the "FormType" field.
func FormTypeHasPrefix(v string) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldFormType), v))
	})
}

// FormTypeHasSuffix applies the HasSuffix predicate on the "FormType" field.
func FormTypeHasSuffix(v string) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldFormType), v))
	})
}

// FormTypeEqualFold applies the EqualFold predicate on the "FormType" field.
func FormTypeEqualFold(v string) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldFormType), v))
	})
}

// FormTypeContainsFold applies the ContainsFold predicate on the "FormType" field.
func FormTypeContainsFold(v string) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldFormType), v))
	})
}

// HasDrugs applies the HasEdge predicate on the "drugs" edge.
func HasDrugs() predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DrugsTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DrugsTable, DrugsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDrugsWith applies the HasEdge predicate on the "drugs" edge with a given conditions (other predicates).
func HasDrugsWith(preds ...predicate.Drug) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DrugsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DrugsTable, DrugsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Form) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Form) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Form) predicate.Form {
	return predicate.Form(func(s *sql.Selector) {
		p(s.Not())
	})
}
