// Code generated by entc, DO NOT EDIT.

package dispense

const (
	// Label holds the string label denoting the dispense type in the database.
	Label = "dispense"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"

	// EdgeDrug holds the string denoting the drug edge name in mutations.
	EdgeDrug = "drug"
	// EdgeUsers holds the string denoting the users edge name in mutations.
	EdgeUsers = "users"
	// EdgeDrugs holds the string denoting the drugs edge name in mutations.
	EdgeDrugs = "drugs"

	// Table holds the table name of the dispense in the database.
	Table = "dispenses"
	// DrugTable is the table the holds the drug relation/edge.
	DrugTable = "dispenses"
	// DrugInverseTable is the table name for the Drug entity.
	// It exists in this package in order to avoid circular dependency with the "drug" package.
	DrugInverseTable = "drugs"
	// DrugColumn is the table column denoting the drug relation/edge.
	DrugColumn = "drug_id"
	// UsersTable is the table the holds the users relation/edge.
	UsersTable = "users"
	// UsersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UsersInverseTable = "users"
	// UsersColumn is the table column denoting the users relation/edge.
	UsersColumn = "dispense_id"
	// DrugsTable is the table the holds the drugs relation/edge.
	DrugsTable = "drugs"
	// DrugsInverseTable is the table name for the Drug entity.
	// It exists in this package in order to avoid circular dependency with the "drug" package.
	DrugsInverseTable = "drugs"
	// DrugsColumn is the table column denoting the drugs relation/edge.
	DrugsColumn = "dispense_id"
)

// Columns holds all SQL columns for dispense fields.
var Columns = []string{
	FieldID,
	FieldNote,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Dispense type.
var ForeignKeys = []string{
	"drug_id",
}

var (
	// NoteValidator is a validator for the "note" field. It is called by the builders before save.
	NoteValidator func(string) error
)
