// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/Piichet-3-/app/ent/dispense"
	"github.com/Piichet-3-/app/ent/drug"
	"github.com/Piichet-3-/app/ent/predicate"
	"github.com/Piichet-3-/app/ent/user"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// DispenseUpdate is the builder for updating Dispense entities.
type DispenseUpdate struct {
	config
	hooks      []Hook
	mutation   *DispenseMutation
	predicates []predicate.Dispense
}

// Where adds a new predicate for the builder.
func (du *DispenseUpdate) Where(ps ...predicate.Dispense) *DispenseUpdate {
	du.predicates = append(du.predicates, ps...)
	return du
}

// SetNote sets the note field.
func (du *DispenseUpdate) SetNote(s string) *DispenseUpdate {
	du.mutation.SetNote(s)
	return du
}

// SetDrugID sets the drug edge to Drug by id.
func (du *DispenseUpdate) SetDrugID(id int) *DispenseUpdate {
	du.mutation.SetDrugID(id)
	return du
}

// SetNillableDrugID sets the drug edge to Drug by id if the given value is not nil.
func (du *DispenseUpdate) SetNillableDrugID(id *int) *DispenseUpdate {
	if id != nil {
		du = du.SetDrugID(*id)
	}
	return du
}

// SetDrug sets the drug edge to Drug.
func (du *DispenseUpdate) SetDrug(d *Drug) *DispenseUpdate {
	return du.SetDrugID(d.ID)
}

// AddUserIDs adds the users edge to User by ids.
func (du *DispenseUpdate) AddUserIDs(ids ...int) *DispenseUpdate {
	du.mutation.AddUserIDs(ids...)
	return du
}

// AddUsers adds the users edges to User.
func (du *DispenseUpdate) AddUsers(u ...*User) *DispenseUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return du.AddUserIDs(ids...)
}

// AddDrugIDs adds the drugs edge to Drug by ids.
func (du *DispenseUpdate) AddDrugIDs(ids ...int) *DispenseUpdate {
	du.mutation.AddDrugIDs(ids...)
	return du
}

// AddDrugs adds the drugs edges to Drug.
func (du *DispenseUpdate) AddDrugs(d ...*Drug) *DispenseUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return du.AddDrugIDs(ids...)
}

// Mutation returns the DispenseMutation object of the builder.
func (du *DispenseUpdate) Mutation() *DispenseMutation {
	return du.mutation
}

// ClearDrug clears the drug edge to Drug.
func (du *DispenseUpdate) ClearDrug() *DispenseUpdate {
	du.mutation.ClearDrug()
	return du
}

// RemoveUserIDs removes the users edge to User by ids.
func (du *DispenseUpdate) RemoveUserIDs(ids ...int) *DispenseUpdate {
	du.mutation.RemoveUserIDs(ids...)
	return du
}

// RemoveUsers removes users edges to User.
func (du *DispenseUpdate) RemoveUsers(u ...*User) *DispenseUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return du.RemoveUserIDs(ids...)
}

// RemoveDrugIDs removes the drugs edge to Drug by ids.
func (du *DispenseUpdate) RemoveDrugIDs(ids ...int) *DispenseUpdate {
	du.mutation.RemoveDrugIDs(ids...)
	return du
}

// RemoveDrugs removes drugs edges to Drug.
func (du *DispenseUpdate) RemoveDrugs(d ...*Drug) *DispenseUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return du.RemoveDrugIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (du *DispenseUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := du.mutation.Note(); ok {
		if err := dispense.NoteValidator(v); err != nil {
			return 0, &ValidationError{Name: "note", err: fmt.Errorf("ent: validator failed for field \"note\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(du.hooks) == 0 {
		affected, err = du.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DispenseMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			du.mutation = mutation
			affected, err = du.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(du.hooks) - 1; i >= 0; i-- {
			mut = du.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, du.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (du *DispenseUpdate) SaveX(ctx context.Context) int {
	affected, err := du.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (du *DispenseUpdate) Exec(ctx context.Context) error {
	_, err := du.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (du *DispenseUpdate) ExecX(ctx context.Context) {
	if err := du.Exec(ctx); err != nil {
		panic(err)
	}
}

func (du *DispenseUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   dispense.Table,
			Columns: dispense.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: dispense.FieldID,
			},
		},
	}
	if ps := du.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := du.mutation.Note(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: dispense.FieldNote,
		})
	}
	if du.mutation.DrugCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dispense.DrugTable,
			Columns: []string{dispense.DrugColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: drug.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.DrugIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dispense.DrugTable,
			Columns: []string{dispense.DrugColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: drug.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := du.mutation.RemovedUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dispense.UsersTable,
			Columns: []string{dispense.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dispense.UsersTable,
			Columns: []string{dispense.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := du.mutation.RemovedDrugsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dispense.DrugsTable,
			Columns: []string{dispense.DrugsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: drug.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := du.mutation.DrugsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dispense.DrugsTable,
			Columns: []string{dispense.DrugsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: drug.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, du.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dispense.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// DispenseUpdateOne is the builder for updating a single Dispense entity.
type DispenseUpdateOne struct {
	config
	hooks    []Hook
	mutation *DispenseMutation
}

// SetNote sets the note field.
func (duo *DispenseUpdateOne) SetNote(s string) *DispenseUpdateOne {
	duo.mutation.SetNote(s)
	return duo
}

// SetDrugID sets the drug edge to Drug by id.
func (duo *DispenseUpdateOne) SetDrugID(id int) *DispenseUpdateOne {
	duo.mutation.SetDrugID(id)
	return duo
}

// SetNillableDrugID sets the drug edge to Drug by id if the given value is not nil.
func (duo *DispenseUpdateOne) SetNillableDrugID(id *int) *DispenseUpdateOne {
	if id != nil {
		duo = duo.SetDrugID(*id)
	}
	return duo
}

// SetDrug sets the drug edge to Drug.
func (duo *DispenseUpdateOne) SetDrug(d *Drug) *DispenseUpdateOne {
	return duo.SetDrugID(d.ID)
}

// AddUserIDs adds the users edge to User by ids.
func (duo *DispenseUpdateOne) AddUserIDs(ids ...int) *DispenseUpdateOne {
	duo.mutation.AddUserIDs(ids...)
	return duo
}

// AddUsers adds the users edges to User.
func (duo *DispenseUpdateOne) AddUsers(u ...*User) *DispenseUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return duo.AddUserIDs(ids...)
}

// AddDrugIDs adds the drugs edge to Drug by ids.
func (duo *DispenseUpdateOne) AddDrugIDs(ids ...int) *DispenseUpdateOne {
	duo.mutation.AddDrugIDs(ids...)
	return duo
}

// AddDrugs adds the drugs edges to Drug.
func (duo *DispenseUpdateOne) AddDrugs(d ...*Drug) *DispenseUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return duo.AddDrugIDs(ids...)
}

// Mutation returns the DispenseMutation object of the builder.
func (duo *DispenseUpdateOne) Mutation() *DispenseMutation {
	return duo.mutation
}

// ClearDrug clears the drug edge to Drug.
func (duo *DispenseUpdateOne) ClearDrug() *DispenseUpdateOne {
	duo.mutation.ClearDrug()
	return duo
}

// RemoveUserIDs removes the users edge to User by ids.
func (duo *DispenseUpdateOne) RemoveUserIDs(ids ...int) *DispenseUpdateOne {
	duo.mutation.RemoveUserIDs(ids...)
	return duo
}

// RemoveUsers removes users edges to User.
func (duo *DispenseUpdateOne) RemoveUsers(u ...*User) *DispenseUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return duo.RemoveUserIDs(ids...)
}

// RemoveDrugIDs removes the drugs edge to Drug by ids.
func (duo *DispenseUpdateOne) RemoveDrugIDs(ids ...int) *DispenseUpdateOne {
	duo.mutation.RemoveDrugIDs(ids...)
	return duo
}

// RemoveDrugs removes drugs edges to Drug.
func (duo *DispenseUpdateOne) RemoveDrugs(d ...*Drug) *DispenseUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return duo.RemoveDrugIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (duo *DispenseUpdateOne) Save(ctx context.Context) (*Dispense, error) {
	if v, ok := duo.mutation.Note(); ok {
		if err := dispense.NoteValidator(v); err != nil {
			return nil, &ValidationError{Name: "note", err: fmt.Errorf("ent: validator failed for field \"note\": %w", err)}
		}
	}

	var (
		err  error
		node *Dispense
	)
	if len(duo.hooks) == 0 {
		node, err = duo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DispenseMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			duo.mutation = mutation
			node, err = duo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(duo.hooks) - 1; i >= 0; i-- {
			mut = duo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, duo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (duo *DispenseUpdateOne) SaveX(ctx context.Context) *Dispense {
	d, err := duo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return d
}

// Exec executes the query on the entity.
func (duo *DispenseUpdateOne) Exec(ctx context.Context) error {
	_, err := duo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (duo *DispenseUpdateOne) ExecX(ctx context.Context) {
	if err := duo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (duo *DispenseUpdateOne) sqlSave(ctx context.Context) (d *Dispense, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   dispense.Table,
			Columns: dispense.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: dispense.FieldID,
			},
		},
	}
	id, ok := duo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Dispense.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := duo.mutation.Note(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: dispense.FieldNote,
		})
	}
	if duo.mutation.DrugCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dispense.DrugTable,
			Columns: []string{dispense.DrugColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: drug.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.DrugIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dispense.DrugTable,
			Columns: []string{dispense.DrugColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: drug.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := duo.mutation.RemovedUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dispense.UsersTable,
			Columns: []string{dispense.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dispense.UsersTable,
			Columns: []string{dispense.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := duo.mutation.RemovedDrugsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dispense.DrugsTable,
			Columns: []string{dispense.DrugsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: drug.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := duo.mutation.DrugsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dispense.DrugsTable,
			Columns: []string{dispense.DrugsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: drug.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	d = &Dispense{config: duo.config}
	_spec.Assign = d.assignValues
	_spec.ScanValues = d.scanValues()
	if err = sqlgraph.UpdateNode(ctx, duo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dispense.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return d, nil
}
