// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/Piichet-3-/app/ent/drug"
	"github.com/Piichet-3-/app/ent/form"
	"github.com/Piichet-3-/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// FormUpdate is the builder for updating Form entities.
type FormUpdate struct {
	config
	hooks      []Hook
	mutation   *FormMutation
	predicates []predicate.Form
}

// Where adds a new predicate for the builder.
func (fu *FormUpdate) Where(ps ...predicate.Form) *FormUpdate {
	fu.predicates = append(fu.predicates, ps...)
	return fu
}

// SetFormType sets the FormType field.
func (fu *FormUpdate) SetFormType(s string) *FormUpdate {
	fu.mutation.SetFormType(s)
	return fu
}

// AddDrugIDs adds the drugs edge to Drug by ids.
func (fu *FormUpdate) AddDrugIDs(ids ...int) *FormUpdate {
	fu.mutation.AddDrugIDs(ids...)
	return fu
}

// AddDrugs adds the drugs edges to Drug.
func (fu *FormUpdate) AddDrugs(d ...*Drug) *FormUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return fu.AddDrugIDs(ids...)
}

// Mutation returns the FormMutation object of the builder.
func (fu *FormUpdate) Mutation() *FormMutation {
	return fu.mutation
}

// RemoveDrugIDs removes the drugs edge to Drug by ids.
func (fu *FormUpdate) RemoveDrugIDs(ids ...int) *FormUpdate {
	fu.mutation.RemoveDrugIDs(ids...)
	return fu
}

// RemoveDrugs removes drugs edges to Drug.
func (fu *FormUpdate) RemoveDrugs(d ...*Drug) *FormUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return fu.RemoveDrugIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (fu *FormUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := fu.mutation.FormType(); ok {
		if err := form.FormTypeValidator(v); err != nil {
			return 0, &ValidationError{Name: "FormType", err: fmt.Errorf("ent: validator failed for field \"FormType\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(fu.hooks) == 0 {
		affected, err = fu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FormMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			fu.mutation = mutation
			affected, err = fu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(fu.hooks) - 1; i >= 0; i-- {
			mut = fu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, fu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (fu *FormUpdate) SaveX(ctx context.Context) int {
	affected, err := fu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fu *FormUpdate) Exec(ctx context.Context) error {
	_, err := fu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fu *FormUpdate) ExecX(ctx context.Context) {
	if err := fu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (fu *FormUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   form.Table,
			Columns: form.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: form.FieldID,
			},
		},
	}
	if ps := fu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fu.mutation.FormType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: form.FieldFormType,
		})
	}
	if nodes := fu.mutation.RemovedDrugsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   form.DrugsTable,
			Columns: []string{form.DrugsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: drug.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.DrugsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   form.DrugsTable,
			Columns: []string{form.DrugsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: drug.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{form.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// FormUpdateOne is the builder for updating a single Form entity.
type FormUpdateOne struct {
	config
	hooks    []Hook
	mutation *FormMutation
}

// SetFormType sets the FormType field.
func (fuo *FormUpdateOne) SetFormType(s string) *FormUpdateOne {
	fuo.mutation.SetFormType(s)
	return fuo
}

// AddDrugIDs adds the drugs edge to Drug by ids.
func (fuo *FormUpdateOne) AddDrugIDs(ids ...int) *FormUpdateOne {
	fuo.mutation.AddDrugIDs(ids...)
	return fuo
}

// AddDrugs adds the drugs edges to Drug.
func (fuo *FormUpdateOne) AddDrugs(d ...*Drug) *FormUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return fuo.AddDrugIDs(ids...)
}

// Mutation returns the FormMutation object of the builder.
func (fuo *FormUpdateOne) Mutation() *FormMutation {
	return fuo.mutation
}

// RemoveDrugIDs removes the drugs edge to Drug by ids.
func (fuo *FormUpdateOne) RemoveDrugIDs(ids ...int) *FormUpdateOne {
	fuo.mutation.RemoveDrugIDs(ids...)
	return fuo
}

// RemoveDrugs removes drugs edges to Drug.
func (fuo *FormUpdateOne) RemoveDrugs(d ...*Drug) *FormUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return fuo.RemoveDrugIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (fuo *FormUpdateOne) Save(ctx context.Context) (*Form, error) {
	if v, ok := fuo.mutation.FormType(); ok {
		if err := form.FormTypeValidator(v); err != nil {
			return nil, &ValidationError{Name: "FormType", err: fmt.Errorf("ent: validator failed for field \"FormType\": %w", err)}
		}
	}

	var (
		err  error
		node *Form
	)
	if len(fuo.hooks) == 0 {
		node, err = fuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FormMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			fuo.mutation = mutation
			node, err = fuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(fuo.hooks) - 1; i >= 0; i-- {
			mut = fuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, fuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (fuo *FormUpdateOne) SaveX(ctx context.Context) *Form {
	f, err := fuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return f
}

// Exec executes the query on the entity.
func (fuo *FormUpdateOne) Exec(ctx context.Context) error {
	_, err := fuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fuo *FormUpdateOne) ExecX(ctx context.Context) {
	if err := fuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (fuo *FormUpdateOne) sqlSave(ctx context.Context) (f *Form, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   form.Table,
			Columns: form.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: form.FieldID,
			},
		},
	}
	id, ok := fuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Form.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := fuo.mutation.FormType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: form.FieldFormType,
		})
	}
	if nodes := fuo.mutation.RemovedDrugsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   form.DrugsTable,
			Columns: []string{form.DrugsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: drug.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.DrugsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   form.DrugsTable,
			Columns: []string{form.DrugsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: drug.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	f = &Form{config: fuo.config}
	_spec.Assign = f.assignValues
	_spec.ScanValues = f.scanValues()
	if err = sqlgraph.UpdateNode(ctx, fuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{form.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return f, nil
}
