// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/Piichet-3-/app/ent/drug"
	"github.com/Piichet-3-/app/ent/unit"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// UnitCreate is the builder for creating a Unit entity.
type UnitCreate struct {
	config
	mutation *UnitMutation
	hooks    []Hook
}

// SetUnitType sets the UnitType field.
func (uc *UnitCreate) SetUnitType(s string) *UnitCreate {
	uc.mutation.SetUnitType(s)
	return uc
}

// AddDrugIDs adds the drugs edge to Drug by ids.
func (uc *UnitCreate) AddDrugIDs(ids ...int) *UnitCreate {
	uc.mutation.AddDrugIDs(ids...)
	return uc
}

// AddDrugs adds the drugs edges to Drug.
func (uc *UnitCreate) AddDrugs(d ...*Drug) *UnitCreate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return uc.AddDrugIDs(ids...)
}

// Mutation returns the UnitMutation object of the builder.
func (uc *UnitCreate) Mutation() *UnitMutation {
	return uc.mutation
}

// Save creates the Unit in the database.
func (uc *UnitCreate) Save(ctx context.Context) (*Unit, error) {
	if _, ok := uc.mutation.UnitType(); !ok {
		return nil, &ValidationError{Name: "UnitType", err: errors.New("ent: missing required field \"UnitType\"")}
	}
	if v, ok := uc.mutation.UnitType(); ok {
		if err := unit.UnitTypeValidator(v); err != nil {
			return nil, &ValidationError{Name: "UnitType", err: fmt.Errorf("ent: validator failed for field \"UnitType\": %w", err)}
		}
	}
	var (
		err  error
		node *Unit
	)
	if len(uc.hooks) == 0 {
		node, err = uc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UnitMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uc.mutation = mutation
			node, err = uc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(uc.hooks) - 1; i >= 0; i-- {
			mut = uc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (uc *UnitCreate) SaveX(ctx context.Context) *Unit {
	v, err := uc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uc *UnitCreate) sqlSave(ctx context.Context) (*Unit, error) {
	u, _spec := uc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	u.ID = int(id)
	return u, nil
}

func (uc *UnitCreate) createSpec() (*Unit, *sqlgraph.CreateSpec) {
	var (
		u     = &Unit{config: uc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: unit.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: unit.FieldID,
			},
		}
	)
	if value, ok := uc.mutation.UnitType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: unit.FieldUnitType,
		})
		u.UnitType = value
	}
	if nodes := uc.mutation.DrugsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   unit.DrugsTable,
			Columns: []string{unit.DrugsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: drug.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return u, _spec
}
