// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/Piichet-3-/app/ent/unit"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Unit is the model entity for the Unit schema.
type Unit struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UnitType holds the value of the "UnitType" field.
	UnitType string `json:"UnitType,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UnitQuery when eager-loading is set.
	Edges UnitEdges `json:"edges"`
}

// UnitEdges holds the relations/edges for other nodes in the graph.
type UnitEdges struct {
	// Drugs holds the value of the drugs edge.
	Drugs []*Drug
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DrugsOrErr returns the Drugs value or an error if the edge
// was not loaded in eager-loading.
func (e UnitEdges) DrugsOrErr() ([]*Drug, error) {
	if e.loadedTypes[0] {
		return e.Drugs, nil
	}
	return nil, &NotLoadedError{edge: "drugs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Unit) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // UnitType
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Unit fields.
func (u *Unit) assignValues(values ...interface{}) error {
	if m, n := len(values), len(unit.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	u.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field UnitType", values[0])
	} else if value.Valid {
		u.UnitType = value.String
	}
	return nil
}

// QueryDrugs queries the drugs edge of the Unit.
func (u *Unit) QueryDrugs() *DrugQuery {
	return (&UnitClient{config: u.config}).QueryDrugs(u)
}

// Update returns a builder for updating this Unit.
// Note that, you need to call Unit.Unwrap() before calling this method, if this Unit
// was returned from a transaction, and the transaction was committed or rolled back.
func (u *Unit) Update() *UnitUpdateOne {
	return (&UnitClient{config: u.config}).UpdateOne(u)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (u *Unit) Unwrap() *Unit {
	tx, ok := u.config.driver.(*txDriver)
	if !ok {
		panic("ent: Unit is not a transactional entity")
	}
	u.config.driver = tx.drv
	return u
}

// String implements the fmt.Stringer.
func (u *Unit) String() string {
	var builder strings.Builder
	builder.WriteString("Unit(")
	builder.WriteString(fmt.Sprintf("id=%v", u.ID))
	builder.WriteString(", UnitType=")
	builder.WriteString(u.UnitType)
	builder.WriteByte(')')
	return builder.String()
}

// Units is a parsable slice of Unit.
type Units []*Unit

func (u Units) config(cfg config) {
	for _i := range u {
		u[_i].config = cfg
	}
}
