// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/Piichet-3-/app/ent/drug"
	"github.com/Piichet-3-/app/ent/volume"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// VolumeCreate is the builder for creating a Volume entity.
type VolumeCreate struct {
	config
	mutation *VolumeMutation
	hooks    []Hook
}

// SetVolumeType sets the VolumeType field.
func (vc *VolumeCreate) SetVolumeType(s string) *VolumeCreate {
	vc.mutation.SetVolumeType(s)
	return vc
}

// AddDrugIDs adds the drugs edge to Drug by ids.
func (vc *VolumeCreate) AddDrugIDs(ids ...int) *VolumeCreate {
	vc.mutation.AddDrugIDs(ids...)
	return vc
}

// AddDrugs adds the drugs edges to Drug.
func (vc *VolumeCreate) AddDrugs(d ...*Drug) *VolumeCreate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return vc.AddDrugIDs(ids...)
}

// Mutation returns the VolumeMutation object of the builder.
func (vc *VolumeCreate) Mutation() *VolumeMutation {
	return vc.mutation
}

// Save creates the Volume in the database.
func (vc *VolumeCreate) Save(ctx context.Context) (*Volume, error) {
	if _, ok := vc.mutation.VolumeType(); !ok {
		return nil, &ValidationError{Name: "VolumeType", err: errors.New("ent: missing required field \"VolumeType\"")}
	}
	if v, ok := vc.mutation.VolumeType(); ok {
		if err := volume.VolumeTypeValidator(v); err != nil {
			return nil, &ValidationError{Name: "VolumeType", err: fmt.Errorf("ent: validator failed for field \"VolumeType\": %w", err)}
		}
	}
	var (
		err  error
		node *Volume
	)
	if len(vc.hooks) == 0 {
		node, err = vc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*VolumeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			vc.mutation = mutation
			node, err = vc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(vc.hooks) - 1; i >= 0; i-- {
			mut = vc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, vc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (vc *VolumeCreate) SaveX(ctx context.Context) *Volume {
	v, err := vc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (vc *VolumeCreate) sqlSave(ctx context.Context) (*Volume, error) {
	v, _spec := vc.createSpec()
	if err := sqlgraph.CreateNode(ctx, vc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	v.ID = int(id)
	return v, nil
}

func (vc *VolumeCreate) createSpec() (*Volume, *sqlgraph.CreateSpec) {
	var (
		v     = &Volume{config: vc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: volume.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: volume.FieldID,
			},
		}
	)
	if value, ok := vc.mutation.VolumeType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: volume.FieldVolumeType,
		})
		v.VolumeType = value
	}
	if nodes := vc.mutation.DrugsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   volume.DrugsTable,
			Columns: []string{volume.DrugsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: drug.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return v, _spec
}
