// Code generated by entc, DO NOT EDIT.

package unit

const (
	// Label holds the string label denoting the unit type in the database.
	Label = "unit"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUnitType holds the string denoting the unittype field in the database.
	FieldUnitType = "unit_type"

	// EdgeDrugs holds the string denoting the drugs edge name in mutations.
	EdgeDrugs = "drugs"

	// Table holds the table name of the unit in the database.
	Table = "units"
	// DrugsTable is the table the holds the drugs relation/edge.
	DrugsTable = "drugs"
	// DrugsInverseTable is the table name for the Drug entity.
	// It exists in this package in order to avoid circular dependency with the "drug" package.
	DrugsInverseTable = "drugs"
	// DrugsColumn is the table column denoting the drugs relation/edge.
	DrugsColumn = "unit_id"
)

// Columns holds all SQL columns for unit fields.
var Columns = []string{
	FieldID,
	FieldUnitType,
}

var (
	// UnitTypeValidator is a validator for the "UnitType" field. It is called by the builders before save.
	UnitTypeValidator func(string) error
)
